import type { EwayBill } from "./ewaybill.types.js";

const now = () => new Date();
const hoursFromNow = (h: number) =>
  new Date(now().getTime() + h * 60 * 60 * 1000).toISOString();
const hoursAgo = (h: number) =>
  new Date(now().getTime() - h * 60 * 60 * 1000).toISOString();

const SKERP_TRANSPORTER_ID = "29ABCDE1234F1Z5";
const SKERP_TRANSPORTER_NAME = "SK Konnect Logistics Pvt Ltd";

export const seedEwayBills = (): EwayBill[] => [
  {
    ewbNo: "881023456712",
    status: "ACTIVE",
    generatedDate: hoursAgo(6),
    validUntil: hoursFromNow(3),
    docType: "Tax Invoice",
    docNo: "INV/2026/4451",
    docDate: hoursAgo(8),
    fromGstin: "27AAACR5055K1Z5",
    fromTrdName: "Reliance Industries Ltd",
    fromAddr1: "Maker Chambers IV, Nariman Point",
    fromPlace: "Mumbai",
    fromPincode: 400021,
    fromStateCode: 27,
    fromStateName: "Maharashtra",
    toGstin: "29AAGCB7383A1Z6",
    toTrdName: "Bharat Petroleum Corp Ltd",
    toAddr1: "BPCL Logistics Hub, Whitefield",
    toPlace: "Bengaluru",
    toPincode: 560066,
    toStateCode: 29,
    toStateName: "Karnataka",
    transporterId: SKERP_TRANSPORTER_ID,
    transporterName: SKERP_TRANSPORTER_NAME,
    transMode: "ROAD",
    transDistance: 980,
    vehicleNo: "MH04 KL 7821",
    transDocNo: "LR/2026/1112",
    transDocDate: hoursAgo(7),
    totInvValue: 1845320,
    cgstValue: 0,
    sgstValue: 0,
    igstValue: 281320,
    items: [
      {
        productName: "Industrial Lubricant",
        productDesc: "Grade-A Industrial Lubricant 20L drum",
        hsnCode: "27101981",
        quantity: 240,
        qtyUnit: "NOS",
        taxableAmount: 1564000,
      },
    ],
    vehicleHistory: [
      {
        vehicleNo: "MH04 KL 7821",
        fromPlace: "Mumbai",
        fromState: 27,
        updatedAt: hoursAgo(6),
        reasonCode: "4",
        reasonRem: "Initial allocation",
      },
    ],
    extensions: [],
  },
  {
    ewbNo: "881023456713",
    status: "ACTIVE",
    generatedDate: hoursAgo(20),
    validUntil: hoursFromNow(1.5),
    docType: "Tax Invoice",
    docNo: "INV/2026/4452",
    docDate: hoursAgo(22),
    fromGstin: "06AAACT2727Q1ZW",
    fromTrdName: "Maruti Suzuki India Ltd",
    fromAddr1: "Plot No 1, Maruti Industrial Area",
    fromPlace: "Gurugram",
    fromPincode: 122015,
    fromStateCode: 6,
    fromStateName: "Haryana",
    toGstin: "29AAGCB7383A1Z6",
    toTrdName: "South India Auto Dealers",
    toAddr1: "Hosur Road, Electronic City",
    toPlace: "Bengaluru",
    toPincode: 560100,
    toStateCode: 29,
    toStateName: "Karnataka",
    transporterId: SKERP_TRANSPORTER_ID,
    transporterName: SKERP_TRANSPORTER_NAME,
    transMode: "ROAD",
    transDistance: 2120,
    vehicleNo: "HR55 AT 4412",
    transDocNo: "LR/2026/1098",
    transDocDate: hoursAgo(21),
    totInvValue: 8920000,
    cgstValue: 0,
    sgstValue: 0,
    igstValue: 1605600,
    items: [
      {
        productName: "Auto Spare Parts",
        productDesc: "Assorted Maruti genuine spare parts",
        hsnCode: "87089900",
        quantity: 18,
        qtyUnit: "BOX",
        taxableAmount: 7314400,
      },
    ],
    vehicleHistory: [
      {
        vehicleNo: "HR55 AT 4412",
        fromPlace: "Gurugram",
        fromState: 6,
        updatedAt: hoursAgo(20),
        reasonCode: "4",
        reasonRem: "Initial allocation",
      },
    ],
    extensions: [],
  },
  {
    ewbNo: "881023456714",
    status: "PART_B_PENDING",
    generatedDate: hoursAgo(2),
    validUntil: hoursFromNow(22),
    docType: "Tax Invoice",
    docNo: "INV/2026/4500",
    docDate: hoursAgo(3),
    fromGstin: "33AAACH7791L1Z3",
    fromTrdName: "Hindustan Unilever Ltd",
    fromAddr1: "HUL Distribution Centre, Sriperumbudur",
    fromPlace: "Chennai",
    fromPincode: 602105,
    fromStateCode: 33,
    fromStateName: "Tamil Nadu",
    toGstin: "32AABCM3415G1Z2",
    toTrdName: "Margin Free Markets",
    toAddr1: "MG Road",
    toPlace: "Kochi",
    toPincode: 682035,
    toStateCode: 32,
    toStateName: "Kerala",
    transporterId: SKERP_TRANSPORTER_ID,
    transporterName: SKERP_TRANSPORTER_NAME,
    transMode: "ROAD",
    transDistance: 690,
    vehicleNo: "",
    totInvValue: 412800,
    cgstValue: 0,
    sgstValue: 0,
    igstValue: 62971,
    items: [
      {
        productName: "FMCG Assorted",
        productDesc: "Detergents, soaps, personal care",
        hsnCode: "34022090",
        quantity: 480,
        qtyUnit: "CTN",
        taxableAmount: 349829,
      },
    ],
    vehicleHistory: [],
    extensions: [],
  },
  {
    ewbNo: "881023456715",
    status: "IN_TRANSIT",
    generatedDate: hoursAgo(14),
    validUntil: hoursFromNow(34),
    docType: "Tax Invoice",
    docNo: "INV/2026/4488",
    docDate: hoursAgo(16),
    fromGstin: "24AAACD9824A1ZV",
    fromTrdName: "Adani Wilmar Ltd",
    fromAddr1: "Adani House, Mundra Port",
    fromPlace: "Mundra",
    fromPincode: 370421,
    fromStateCode: 24,
    fromStateName: "Gujarat",
    toGstin: "27AAACR5055K1Z5",
    toTrdName: "DMart Wholesale",
    toAddr1: "Bhiwandi Distribution Hub",
    toPlace: "Bhiwandi",
    toPincode: 421302,
    toStateCode: 27,
    toStateName: "Maharashtra",
    transporterId: SKERP_TRANSPORTER_ID,
    transporterName: SKERP_TRANSPORTER_NAME,
    transMode: "ROAD",
    transDistance: 720,
    vehicleNo: "GJ12 BX 9911",
    transDocNo: "LR/2026/1077",
    transDocDate: hoursAgo(15),
    totInvValue: 2340000,
    cgstValue: 0,
    sgstValue: 0,
    igstValue: 117000,
    items: [
      {
        productName: "Edible Oil",
        productDesc: "Fortune Sunflower Oil 1L pouches",
        hsnCode: "15121100",
        quantity: 12000,
        qtyUnit: "NOS",
        taxableAmount: 2223000,
      },
    ],
    vehicleHistory: [
      {
        vehicleNo: "GJ12 BX 9911",
        fromPlace: "Mundra",
        fromState: 24,
        updatedAt: hoursAgo(14),
        reasonCode: "4",
        reasonRem: "Initial allocation",
      },
    ],
    extensions: [],
  },
  {
    ewbNo: "881023456716",
    status: "ACTIVE",
    generatedDate: hoursAgo(9),
    validUntil: hoursFromNow(15),
    docType: "Delivery Challan",
    docNo: "DC/2026/0822",
    docDate: hoursAgo(10),
    fromGstin: "27AAACR5055K1Z5",
    fromTrdName: "Tata Steel Ltd",
    fromAddr1: "Tata Centre, Jamshedpur",
    fromPlace: "Jamshedpur",
    fromPincode: 831001,
    fromStateCode: 20,
    fromStateName: "Jharkhand",
    toGstin: "19AABCT3518Q1ZS",
    toTrdName: "Howrah Construction Co",
    toAddr1: "GT Road, Howrah",
    toPlace: "Howrah",
    toPincode: 711101,
    toStateCode: 19,
    toStateName: "West Bengal",
    transporterId: SKERP_TRANSPORTER_ID,
    transporterName: SKERP_TRANSPORTER_NAME,
    transMode: "ROAD",
    transDistance: 280,
    vehicleNo: "JH05 CD 2244",
    transDocNo: "LR/2026/1145",
    transDocDate: hoursAgo(9),
    totInvValue: 1240000,
    cgstValue: 0,
    sgstValue: 0,
    igstValue: 189153,
    items: [
      {
        productName: "TMT Steel Bars",
        productDesc: "Fe-500D TMT bars 12mm",
        hsnCode: "72142010",
        quantity: 22,
        qtyUnit: "MT",
        taxableAmount: 1050847,
      },
    ],
    vehicleHistory: [
      {
        vehicleNo: "JH05 CD 2244",
        fromPlace: "Jamshedpur",
        fromState: 20,
        updatedAt: hoursAgo(9),
        reasonCode: "4",
        reasonRem: "Initial allocation",
      },
    ],
    extensions: [],
  },
  {
    ewbNo: "881023456717",
    status: "ACTIVE",
    generatedDate: hoursAgo(3),
    validUntil: hoursFromNow(45),
    docType: "Tax Invoice",
    docNo: "INV/2026/4561",
    docDate: hoursAgo(4),
    fromGstin: "29AAGCB7383A1Z6",
    fromTrdName: "Infosys Ltd",
    fromAddr1: "Electronics City, Phase-1",
    fromPlace: "Bengaluru",
    fromPincode: 560100,
    fromStateCode: 29,
    fromStateName: "Karnataka",
    toGstin: "27AAACR5055K1Z5",
    toTrdName: "Infosys BKC Office",
    toAddr1: "Bandra Kurla Complex",
    toPlace: "Mumbai",
    toPincode: 400051,
    toStateCode: 27,
    toStateName: "Maharashtra",
    transporterId: SKERP_TRANSPORTER_ID,
    transporterName: SKERP_TRANSPORTER_NAME,
    transMode: "ROAD",
    transDistance: 980,
    vehicleNo: "KA01 MZ 8800",
    transDocNo: "LR/2026/1180",
    transDocDate: hoursAgo(3),
    totInvValue: 580000,
    cgstValue: 0,
    sgstValue: 0,
    igstValue: 88474,
    items: [
      {
        productName: "IT Equipment",
        productDesc: "Workstations and accessories",
        hsnCode: "84714900",
        quantity: 48,
        qtyUnit: "NOS",
        taxableAmount: 491526,
      },
    ],
    vehicleHistory: [
      {
        vehicleNo: "KA01 MZ 8800",
        fromPlace: "Bengaluru",
        fromState: 29,
        updatedAt: hoursAgo(3),
        reasonCode: "4",
        reasonRem: "Initial allocation",
      },
    ],
    extensions: [],
  },
  {
    ewbNo: "881023456718",
    status: "DELIVERED",
    generatedDate: hoursAgo(38),
    validUntil: hoursAgo(2),
    docType: "Tax Invoice",
    docNo: "INV/2026/4401",
    docDate: hoursAgo(40),
    fromGstin: "07AAACI1681G1ZN",
    fromTrdName: "ITC Limited",
    fromAddr1: "ITC Centre, Connaught Place",
    fromPlace: "New Delhi",
    fromPincode: 110001,
    fromStateCode: 7,
    fromStateName: "Delhi",
    toGstin: "27AAACR5055K1Z5",
    toTrdName: "Star Bazaar Mumbai",
    toAddr1: "Andheri West",
    toPlace: "Mumbai",
    toPincode: 400053,
    toStateCode: 27,
    toStateName: "Maharashtra",
    transporterId: SKERP_TRANSPORTER_ID,
    transporterName: SKERP_TRANSPORTER_NAME,
    transMode: "ROAD",
    transDistance: 1410,
    vehicleNo: "DL01 PB 6677",
    transDocNo: "LR/2026/1042",
    transDocDate: hoursAgo(37),
    totInvValue: 765000,
    cgstValue: 0,
    sgstValue: 0,
    igstValue: 116695,
    items: [
      {
        productName: "Packaged Foods",
        productDesc: "Aashirvaad atta, biscuits, noodles",
        hsnCode: "11010000",
        quantity: 800,
        qtyUnit: "CTN",
        taxableAmount: 648305,
      },
    ],
    vehicleHistory: [
      {
        vehicleNo: "DL01 PB 6677",
        fromPlace: "New Delhi",
        fromState: 7,
        updatedAt: hoursAgo(38),
        reasonCode: "4",
        reasonRem: "Initial allocation",
      },
    ],
    extensions: [],
  },
  {
    ewbNo: "881023456719",
    status: "ACTIVE",
    generatedDate: hoursAgo(11),
    validUntil: hoursFromNow(60),
    docType: "Tax Invoice",
    docNo: "INV/2026/4470",
    docDate: hoursAgo(12),
    fromGstin: "08AABCU9603R1ZM",
    fromTrdName: "JK Cement Ltd",
    fromAddr1: "Mangrol Plant",
    fromPlace: "Mangrol",
    fromPincode: 326519,
    fromStateCode: 8,
    fromStateName: "Rajasthan",
    toGstin: "06AAACT2727Q1ZW",
    toTrdName: "DLF Construction Hub",
    toAddr1: "Sector 53, Golf Course Road",
    toPlace: "Gurugram",
    toPincode: 122002,
    toStateCode: 6,
    toStateName: "Haryana",
    transporterId: SKERP_TRANSPORTER_ID,
    transporterName: SKERP_TRANSPORTER_NAME,
    transMode: "ROAD",
    transDistance: 520,
    vehicleNo: "RJ20 GA 1199",
    transDocNo: "LR/2026/1156",
    transDocDate: hoursAgo(11),
    totInvValue: 980000,
    cgstValue: 0,
    sgstValue: 0,
    igstValue: 149492,
    items: [
      {
        productName: "OPC 53 Cement",
        productDesc: "JK Cement OPC Grade 53, 50kg bags",
        hsnCode: "25232930",
        quantity: 2400,
        qtyUnit: "BAG",
        taxableAmount: 830508,
      },
    ],
    vehicleHistory: [
      {
        vehicleNo: "RJ20 GA 1199",
        fromPlace: "Mangrol",
        fromState: 8,
        updatedAt: hoursAgo(11),
        reasonCode: "4",
        reasonRem: "Initial allocation",
      },
    ],
    extensions: [],
  },
  {
    ewbNo: "881023456720",
    status: "EXPIRED",
    generatedDate: hoursAgo(54),
    validUntil: hoursAgo(8),
    docType: "Tax Invoice",
    docNo: "INV/2026/4380",
    docDate: hoursAgo(56),
    fromGstin: "27AAACR5055K1Z5",
    fromTrdName: "Asian Paints Ltd",
    fromAddr1: "Khandala Plant",
    fromPlace: "Khandala",
    fromPincode: 410301,
    fromStateCode: 27,
    fromStateName: "Maharashtra",
    toGstin: "36AAACH7791L1Z2",
    toTrdName: "Hyderabad Hardware",
    toAddr1: "Begumpet",
    toPlace: "Hyderabad",
    toPincode: 500016,
    toStateCode: 36,
    toStateName: "Telangana",
    transporterId: SKERP_TRANSPORTER_ID,
    transporterName: SKERP_TRANSPORTER_NAME,
    transMode: "ROAD",
    transDistance: 720,
    vehicleNo: "MH14 RG 5566",
    transDocNo: "LR/2026/1011",
    transDocDate: hoursAgo(53),
    totInvValue: 320000,
    cgstValue: 0,
    sgstValue: 0,
    igstValue: 48814,
    items: [
      {
        productName: "Decorative Paints",
        productDesc: "Tractor Emulsion 20L",
        hsnCode: "32091010",
        quantity: 80,
        qtyUnit: "NOS",
        taxableAmount: 271186,
      },
    ],
    vehicleHistory: [
      {
        vehicleNo: "MH14 RG 5566",
        fromPlace: "Khandala",
        fromState: 27,
        updatedAt: hoursAgo(54),
        reasonCode: "4",
        reasonRem: "Initial allocation",
      },
    ],
    extensions: [],
  },
  {
    ewbNo: "881023456721",
    status: "ACTIVE",
    generatedDate: hoursAgo(1),
    validUntil: hoursFromNow(0.5),
    docType: "Tax Invoice",
    docNo: "INV/2026/4570",
    docDate: hoursAgo(2),
    fromGstin: "33AAACH7791L1Z3",
    fromTrdName: "Saint-Gobain India",
    fromAddr1: "Sriperumbudur Glass Plant",
    fromPlace: "Sriperumbudur",
    fromPincode: 602105,
    fromStateCode: 33,
    fromStateName: "Tamil Nadu",
    toGstin: "29AAGCB7383A1Z6",
    toTrdName: "Bengaluru Builders Mart",
    toAddr1: "Yeshwanthpur",
    toPlace: "Bengaluru",
    toPincode: 560022,
    toStateCode: 29,
    toStateName: "Karnataka",
    transporterId: SKERP_TRANSPORTER_ID,
    transporterName: SKERP_TRANSPORTER_NAME,
    transMode: "ROAD",
    transDistance: 350,
    vehicleNo: "TN10 KX 3344",
    transDocNo: "LR/2026/1190",
    transDocDate: hoursAgo(1),
    totInvValue: 615000,
    cgstValue: 0,
    sgstValue: 0,
    igstValue: 93814,
    items: [
      {
        productName: "Float Glass Sheets",
        productDesc: "Clear float glass 6mm",
        hsnCode: "70052990",
        quantity: 120,
        qtyUnit: "SQM",
        taxableAmount: 521186,
      },
    ],
    vehicleHistory: [
      {
        vehicleNo: "TN10 KX 3344",
        fromPlace: "Sriperumbudur",
        fromState: 33,
        updatedAt: hoursAgo(1),
        reasonCode: "4",
        reasonRem: "Initial allocation",
      },
    ],
    extensions: [],
  },
  {
    ewbNo: "881023456722",
    status: "IN_TRANSIT",
    generatedDate: hoursAgo(28),
    validUntil: hoursFromNow(20),
    docType: "Tax Invoice",
    docNo: "INV/2026/4430",
    docDate: hoursAgo(30),
    fromGstin: "24AAACD9824A1ZV",
    fromTrdName: "Cipla Pharmaceuticals",
    fromAddr1: "Patalganga Plant",
    fromPlace: "Patalganga",
    fromPincode: 410220,
    fromStateCode: 27,
    fromStateName: "Maharashtra",
    toGstin: "07AAACI1681G1ZN",
    toTrdName: "Apollo Pharmacy Central",
    toAddr1: "Janakpuri Warehouse",
    toPlace: "New Delhi",
    toPincode: 110058,
    toStateCode: 7,
    toStateName: "Delhi",
    transporterId: SKERP_TRANSPORTER_ID,
    transporterName: SKERP_TRANSPORTER_NAME,
    transMode: "ROAD",
    transDistance: 1410,
    vehicleNo: "MH06 QL 7723",
    transDocNo: "LR/2026/1060",
    transDocDate: hoursAgo(27),
    totInvValue: 1750000,
    cgstValue: 0,
    sgstValue: 0,
    igstValue: 210000,
    items: [
      {
        productName: "Pharmaceuticals",
        productDesc: "Mixed prescription medicines (cold chain)",
        hsnCode: "30049099",
        quantity: 320,
        qtyUnit: "CTN",
        taxableAmount: 1540000,
      },
    ],
    vehicleHistory: [
      {
        vehicleNo: "MH06 QL 7723",
        fromPlace: "Patalganga",
        fromState: 27,
        updatedAt: hoursAgo(28),
        reasonCode: "4",
        reasonRem: "Initial allocation",
      },
    ],
    extensions: [],
  },
  {
    ewbNo: "881023456723",
    status: "ACTIVE",
    generatedDate: hoursAgo(4),
    validUntil: hoursFromNow(44),
    docType: "Tax Invoice",
    docNo: "INV/2026/4555",
    docDate: hoursAgo(5),
    fromGstin: "19AABCT3518Q1ZS",
    fromTrdName: "Britannia Industries",
    fromAddr1: "Taratala Industrial Area",
    fromPlace: "Kolkata",
    fromPincode: 700088,
    fromStateCode: 19,
    fromStateName: "West Bengal",
    toGstin: "20AAACR4849R1Z9",
    toTrdName: "Patna Distributors Inc",
    toAddr1: "Bailey Road",
    toPlace: "Patna",
    toPincode: 800001,
    toStateCode: 10,
    toStateName: "Bihar",
    transporterId: SKERP_TRANSPORTER_ID,
    transporterName: SKERP_TRANSPORTER_NAME,
    transMode: "ROAD",
    transDistance: 580,
    vehicleNo: "WB04 HX 9088",
    transDocNo: "LR/2026/1172",
    transDocDate: hoursAgo(4),
    totInvValue: 420000,
    cgstValue: 0,
    sgstValue: 0,
    igstValue: 64068,
    items: [
      {
        productName: "Biscuits & Snacks",
        productDesc: "Good Day, Marie Gold, NutriChoice",
        hsnCode: "19053100",
        quantity: 1800,
        qtyUnit: "CTN",
        taxableAmount: 355932,
      },
    ],
    vehicleHistory: [
      {
        vehicleNo: "WB04 HX 9088",
        fromPlace: "Kolkata",
        fromState: 19,
        updatedAt: hoursAgo(4),
        reasonCode: "4",
        reasonRem: "Initial allocation",
      },
    ],
    extensions: [],
  },
  {
    ewbNo: "881023456724",
    status: "ACTIVE",
    generatedDate: hoursAgo(7),
    validUntil: hoursFromNow(2.5),
    docType: "Tax Invoice",
    docNo: "INV/2026/4540",
    docDate: hoursAgo(9),
    fromGstin: "06AAACT2727Q1ZW",
    fromTrdName: "Honda Cars India",
    fromAddr1: "Tapukara Plant",
    fromPlace: "Tapukara",
    fromPincode: 301707,
    fromStateCode: 8,
    fromStateName: "Rajasthan",
    toGstin: "33AAACH7791L1Z3",
    toTrdName: "Honda Cars Chennai",
    toAddr1: "OMR Showroom",
    toPlace: "Chennai",
    toPincode: 600097,
    toStateCode: 33,
    toStateName: "Tamil Nadu",
    transporterId: SKERP_TRANSPORTER_ID,
    transporterName: SKERP_TRANSPORTER_NAME,
    transMode: "ROAD",
    transDistance: 2280,
    vehicleNo: "RJ14 LM 5500",
    transDocNo: "LR/2026/1166",
    transDocDate: hoursAgo(7),
    totInvValue: 9560000,
    cgstValue: 0,
    sgstValue: 0,
    igstValue: 1721000,
    items: [
      {
        productName: "Passenger Vehicles",
        productDesc: "Honda City ZX (CBU)",
        hsnCode: "87032391",
        quantity: 6,
        qtyUnit: "NOS",
        taxableAmount: 7839000,
      },
    ],
    vehicleHistory: [
      {
        vehicleNo: "RJ14 LM 5500",
        fromPlace: "Tapukara",
        fromState: 8,
        updatedAt: hoursAgo(7),
        reasonCode: "4",
        reasonRem: "Initial allocation",
      },
    ],
    extensions: [],
  },
  {
    ewbNo: "881023456725",
    status: "PART_B_PENDING",
    generatedDate: hoursAgo(1.5),
    validUntil: hoursFromNow(46),
    docType: "Tax Invoice",
    docNo: "INV/2026/4577",
    docDate: hoursAgo(2),
    fromGstin: "29AAGCB7383A1Z6",
    fromTrdName: "Wipro Consumer Care",
    fromAddr1: "Doddaballapur Plant",
    fromPlace: "Doddaballapur",
    fromPincode: 561203,
    fromStateCode: 29,
    fromStateName: "Karnataka",
    toGstin: "36AAACH7791L1Z2",
    toTrdName: "Hyderabad Modern Trade",
    toAddr1: "Kondapur Hub",
    toPlace: "Hyderabad",
    toPincode: 500084,
    toStateCode: 36,
    toStateName: "Telangana",
    transporterId: SKERP_TRANSPORTER_ID,
    transporterName: SKERP_TRANSPORTER_NAME,
    transMode: "ROAD",
    transDistance: 590,
    vehicleNo: "",
    totInvValue: 280000,
    cgstValue: 0,
    sgstValue: 0,
    igstValue: 42712,
    items: [
      {
        productName: "Personal Care",
        productDesc: "Santoor soaps, Yardley deodorants",
        hsnCode: "34011110",
        quantity: 960,
        qtyUnit: "CTN",
        taxableAmount: 237288,
      },
    ],
    vehicleHistory: [],
    extensions: [],
  },
];
