import type { PERMS } from "./permissions.js";
type Leaves<T> = T extends string
  ? T
  : { [K in keyof T]: Leaves<T[K]> }[keyof T];
// Exhaustive over the registry: a new permission requires a readable name.
const labels = {
  "masters.state.view": "View states",
  "masters.state.create": "Add states",
  "masters.state.update": "Edit states",
  "masters.state.delete": "Delete states",
  "masters.state.bulk_import": "Upload states from a file",
  "masters.state.export": "Download state list",
  "masters.city.view": "View cities",
  "masters.city.create": "Add cities",
  "masters.city.update": "Edit cities",
  "masters.city.delete": "Delete cities",
  "masters.city.bulk_import": "Upload cities from a file",
  "masters.city.export": "Download city list",
  "masters.area.view": "View areas",
  "masters.area.create": "Add areas",
  "masters.area.update": "Edit areas",
  "masters.area.delete": "Delete areas",
  "masters.area.bulk_import": "Upload areas from a file",
  "masters.area.export": "Download area list",
  "masters.transport.view": "View transporters",
  "masters.transport.create": "Add transporters",
  "masters.transport.update": "Edit transporters",
  "masters.transport.delete": "Delete transporters",
  "masters.transport.bulk_import": "Upload transporters from a file",
  "masters.transport.export": "Download transporter list",
  "masters.vehicle.view": "View vehicles",
  "masters.vehicle.create": "Add vehicles",
  "masters.vehicle.update": "Edit vehicles",
  "masters.vehicle.delete": "Delete vehicles",
  "masters.vehicle.bulk_import": "Upload vehicles from a file",
  "masters.vehicle.export": "Download vehicle list",
  "masters.vehicle-type.view": "View vehicle types",
  "masters.vehicle-type.create": "Add vehicle types",
  "masters.vehicle-type.update": "Edit vehicle types",
  "masters.vehicle-type.delete": "Delete vehicle types",
  "masters.vehicle-type.bulk_import": "Upload vehicle types from a file",
  "masters.vehicle-type.export": "Download vehicle type list",
  "masters.spare-category.view": "View spare categories",
  "masters.spare-category.create": "Add spare categories",
  "masters.spare-category.update": "Edit spare categories",
  "masters.spare-category.delete": "Delete spare categories",
  "masters.spare-category.bulk_import": "Upload spare categories from a file",
  "masters.spare-category.export": "Download spare category list",
  "masters.spare-part.view": "View spare parts",
  "masters.spare-part.create": "Add spare parts",
  "masters.spare-part.update": "Edit spare parts",
  "masters.spare-part.delete": "Delete spare parts",
  "masters.spare-part.bulk_import": "Upload spare parts from a file",
  "masters.spare-part.export": "Download spare part list",
  "masters.spare-part-supplier.view": "View spare part suppliers",
  "masters.spare-part-supplier.create": "Add spare part suppliers",
  "masters.spare-part-supplier.update": "Edit spare part suppliers",
  "masters.spare-part-supplier.delete": "Delete spare part suppliers",
  "masters.spare-part-supplier.bulk_import":
    "Upload spare part suppliers from a file",
  "masters.spare-part-supplier.export": "Download spare part supplier list",
  "masters.customer.view": "View customers",
  "masters.customer.create": "Add customers",
  "masters.customer.update": "Edit customers",
  "masters.customer.delete": "Delete customers",
  "masters.customer.bulk_import": "Upload customers from a file",
  "masters.customer.export": "Download customer list",
  "masters.company.view": "View companies",
  "masters.company.create": "Add companies",
  "masters.company.update": "Edit companies",
  "masters.company.delete": "Delete companies",
  "masters.company.bulk_import": "Upload companies from a file",
  "masters.company.export": "Download company list",
  "masters.branch.view": "View branches",
  "masters.branch.create": "Add branches",
  "masters.branch.update": "Edit branches",
  "masters.branch.delete": "Delete branches",
  "masters.branch.bulk_import": "Upload branches from a file",
  "masters.branch.export": "Download branch list",
  "masters.route.view": "View routes",
  "masters.route.create": "Add routes",
  "masters.route.update": "Edit routes",
  "masters.route.delete": "Delete routes",
  "masters.route.bulk_import": "Upload routes from a file",
  "masters.route.export": "Download route list",
  "masters.warehouse.view": "View warehouses",
  "masters.warehouse.create": "Add warehouses",
  "masters.warehouse.update": "Edit warehouses",
  "masters.warehouse.delete": "Delete warehouses",
  "masters.warehouse.bulk_import": "Upload warehouses from a file",
  "masters.warehouse.export": "Download warehouse list",
  "masters.driver.view": "View drivers",
  "masters.driver.create": "Add drivers",
  "masters.driver.update": "Edit drivers",
  "masters.driver.delete": "Delete drivers",
  "masters.driver.bulk_import": "Upload drivers from a file",
  "masters.driver.export": "Download driver list",
  "masters.labour.view": "View labour",
  "masters.labour.create": "Add labour",
  "masters.labour.update": "Edit labour",
  "masters.labour.delete": "Delete labour",
  "masters.labour.bulk_import": "Upload labour from a file",
  "masters.labour.export": "Download labour list",
  "masters.goods.view": "View goods",
  "masters.goods.create": "Add goods",
  "masters.goods.update": "Edit goods",
  "masters.goods.delete": "Delete goods",
  "masters.goods.bulk_import": "Upload goods from a file",
  "masters.goods.export": "Download goods list",
  "masters.unit-of-measure.view": "View units of measure",
  "masters.unit-of-measure.create": "Add units of measure",
  "masters.unit-of-measure.update": "Edit units of measure",
  "masters.unit-of-measure.delete": "Delete units of measure",
  "masters.unit-of-measure.bulk_import": "Upload units of measure from a file",
  "masters.unit-of-measure.export": "Download unit of measure list",
  "masters.pump.view": "View fuel pumps",
  "masters.pump.create": "Add fuel pumps",
  "masters.pump.update": "Edit fuel pumps",
  "masters.pump.delete": "Delete fuel pumps",
  "masters.pump.bulk_import": "Upload fuel pumps from a file",
  "masters.pump.export": "Download fuel pump list",
  "masters.wagon.view": "View wagons",
  "masters.wagon.create": "Add wagons",
  "masters.wagon.update": "Edit wagons",
  "masters.wagon.delete": "Delete wagons",
  "masters.wagon.bulk_import": "Upload wagons from a file",
  "masters.wagon.export": "Download wagon list",
  "masters.railway-freight.view": "View railway freight rates",
  "masters.railway-freight.create": "Add railway freight rates",
  "masters.railway-freight.update": "Edit railway freight rates",
  "masters.railway-freight.delete": "Delete railway freight rates",
  "masters.railway-freight.bulk_import":
    "Upload railway freight rates from a file",
  "masters.railway-freight.export": "Download railway freight rate list",
  "masters.agreement.view": "View agreements",
  "masters.agreement.create": "Add agreements",
  "masters.agreement.update": "Edit agreements",
  "masters.agreement.delete": "Delete agreements",
  "masters.agreement.bulk_import": "Upload agreements from a file",
  "masters.agreement.export": "Download agreement list",
  "masters.rate-matrix.view": "View rate matrices",
  "masters.rate-matrix.create": "Add rate matrices",
  "masters.rate-matrix.update": "Edit rate matrices",
  "masters.rate-matrix.delete": "Delete rate matrices",
  "masters.rate-matrix.bulk_import": "Upload rate matrices from a file",
  "masters.rate-matrix.export": "Download rate matrix list",
  "masters.creditor.view": "View creditors",
  "masters.creditor.create": "Add creditors",
  "masters.creditor.update": "Edit creditors",
  "masters.creditor.delete": "Delete creditors",
  "masters.creditor.bulk_import": "Upload creditors from a file",
  "masters.creditor.export": "Download creditor list",
  "masters.cash-account.view": "View cash accounts",
  "masters.cash-account.create": "Add cash accounts",
  "masters.cash-account.update": "Edit cash accounts",
  "masters.cash-account.delete": "Delete cash accounts",
  "masters.cash-account.bulk_import": "Upload cash accounts from a file",
  "masters.cash-account.export": "Download cash account list",
  "accounts.payment.approve": "Approve vendor payments",
  "accounts.payment.view": "View vendor payments",
  "accounts.payment.create": "Create vendor payments",
  "accounts.payment.disburse": "Pay vendors",
  "accounts.payment.cancel": "Cancel vendor payments",
  "lorry_receipt.view": "View LRs",
  "lorry_receipt.create": "Create LRs",
  "lorry_receipt.update": "Edit LRs",
  "lorry_receipt.delete": "Delete LRs",
  "lorry_receipt.approve": "Approve LRs",
  "lorry_receipt.cancel": "Cancel LRs",
  "lorry_receipt.generate_invoice": "Create bill from LR",
  "lorry_receipt.deliver": "Mark LRs as delivered",
  "lorry_receipt.acknowledge": "Add proof of delivery (POD)",
  "order.view": "View orders",
  "order.create": "Create orders",
  "order.update": "Edit orders",
  "order.delete": "Delete orders",
  "order.approve": "Approve orders",
  "order.reject": "Reject orders",
  "order.cancel": "Cancel orders",
  "trip.view": "View trips",
  "trip.create": "Create trips",
  "trip.update": "Edit trips",
  "trip.delete": "Delete trips",
  "trip.close": "Close trips",
  "trip.cancel": "Cancel trips",
  "trip.correct_closed": "Edit closed trips",
  "trip.correct_in_transit": "Edit trips that are on the road",
  "vehicle_journey.view": "View vehicle journeys",
  "vehicle_journey.create": "Start vehicle journeys",
  "vehicle_journey.update": "Edit vehicle journeys",
  "vehicle_journey.close": "Close vehicle journeys",
  "vehicle_journey.cancel": "Cancel vehicle journeys",
  "vehicle_journey.reopen_settlement": "Reopen settled journeys",
  "vehicle_journey.override_chain": "Add trip out of route order",
  "trip_expense.view": "View trip expenses",
  "trip_expense.create": "Add trip expenses",
  "trip_expense.update": "Edit trip expenses",
  "trip_expense.approve": "Approve trip expenses",
  "trip_expense.reverse": "Undo trip expenses",
  "trip_advance.view": "View driver advances",
  "trip_advance.create": "Give driver advances",
  "trip_advance.reverse": "Undo driver advances",
  "logslip.view": "View log slips",
  "logslip.generate": "Create log slips",
  "logslip.post_accounts": "Send log slips to accounts",
  "logslip.reopen": "Reopen log slips",
  "logslip.print": "Print log slips",
  "vp_schedule.view": "View VP schedule",
  "vp_schedule.create": "Create VP schedule",
  "vp_schedule.update": "Edit VP schedule",
  "vp_schedule.delete": "Delete VP schedule",
  "vp_schedule.confirm": "Confirm VP schedule",
  "vp_schedule.cancel": "Cancel VP schedule",
  "vp_loading.view": "View VP loading",
  "vp_loading.create": "Create VP loading",
  "vp_loading.update": "Edit VP loading",
  "vp_loading.delete": "Delete VP loading",
  "vp_loading.mark_loaded": "Mark a VP as loaded",
  "vp_loading.cancel": "Cancel VP loading",
  "vp_loading.complete": "Complete VP loading",
  "vp_loading.verify": "Verify VP loading",
  "vp_loading.capacity_override": "Load more than VP capacity",
  "vp_loading.assign_tracker": "Add tracker to VP",
  "vp_loading.replace_tracker": "Change tracker on VP",
  "vp_loading.release_tracker": "Remove tracker from VP",
  "mrrr.view": "View MR / RR",
  "mrrr.create": "Create MR / RR",
  "mrrr.update": "Edit MR / RR",
  "mrrr.delete": "Delete MR / RR",
  "mrrr.submit": "Submit MR / RR",
  "mrrr.cancel": "Cancel MR / RR",
  "grn.view": "View GRN at rail head",
  "grn.create": "Create GRN at rail head",
  "grn.update": "Edit GRN at rail head",
  "grn.delete": "Delete GRN at rail head",
  "grn.submit": "Submit GRN at rail head",
  "grn.cancel": "Cancel GRN at rail head",
  "rail_branch_grn.view": "View GRN at branch",
  "rail_branch_grn.create": "Create GRN at branch",
  "rail_branch_grn.update": "Edit GRN at branch",
  "rail_branch_grn.delete": "Delete GRN at branch",
  "rail_branch_grn.submit": "Submit GRN at branch",
  "rail_branch_grn.cancel": "Cancel GRN at branch",
  "rail_rake_operation.view": "View rail rake operations",
  "rail_rake_operation.create": "Create rail rake operations",
  "rail_rake_operation.update": "Edit rail rake operations",
  "rail_rake_operation.delete": "Delete rail rake operations",
  "rail_rake_operation.submit": "Submit rail rake operations",
  "rake_at_rail_head.view": "View rake & DC/WC at rail head",
  "rake_at_rail_head.create": "Create rake & DC/WC at rail head",
  "rake_at_rail_head.update": "Edit rake & DC/WC at rail head",
  "rake_at_rail_head.delete": "Delete rake & DC/WC at rail head",
  "rake_at_rail_head.submit": "Submit rake & DC/WC at rail head",
  "rake_at_branch.view": "View rake & DC/WC at branch",
  "rake_at_branch.create": "Create rake & DC/WC at branch",
  "rake_at_branch.update": "Edit rake & DC/WC at branch",
  "rake_at_branch.delete": "Delete rake & DC/WC at branch",
  "rake_at_branch.submit": "Submit rake & DC/WC at branch",
  "delivery_challan.view": "View delivery challans",
  "delivery_challan.create": "Create delivery challans",
  "delivery_challan.update": "Edit delivery challans",
  "delivery_challan.delete": "Delete delivery challans",
  "delivery_challan.issue": "Issue delivery challans",
  "delivery_challan.cancel": "Cancel delivery challans",
  "ewaybill.view": "View e-way bills",
  "ewaybill.create": "Create e-way bills",
  "ewaybill.update": "Edit e-way bills",
  "ewaybill.delete": "Delete e-way bills",
  "ewaybill.extend": "Extend e-way bills",
  "ewaybill.cancel": "Cancel e-way bills",
  "tracking.view": "View wagon tracking",
  "masters.one-lap-tracker.view": "View OneLap trackers",
  "masters.one-lap-tracker.update": "Edit OneLap trackers",
  "masters.one-lap-tracker.sync": "Update trackers from OneLap",
  "billing.view": "View bills",
  "billing.create": "Create bills",
  "billing.update": "Edit bills",
  "billing.approve": "Approve bills",
  "billing.finalise": "Complete bills",
  "billing.cancel": "Cancel bills",
  "billing.print": "Print bills",
  "billing.charge_approve": "Approve extra charges on bills",
  "billing.tax_rule_manage": "Change GST / tax rules",
  "billing.credit_note_create": "Create credit notes",
  "receipt.view": "View client payments",
  "receipt.create": "Add client payments",
  "receipt.approve": "Approve client payments",
  "receipt.cancel": "Cancel client payments",
  "cashplanning.view": "View cash planning",
  "cashplanning.enter": "Add cash planning amounts",
  "cashplanning.approve": "Approve cash planning",
  "cashplanning.close": "Close the cash planning day",
  "ledger.view": "View ledgers",
  "ledger.voucher_view": "View vouchers",
  "ledger.manage": "Add and edit ledger accounts",
  "ledger.journal_create": "Add journal entries",
  "workshop.po.view": "View purchase orders",
  "workshop.po.manage": "Create and edit purchase orders",
  "workshop.po.approve": "Approve purchase orders",
  "workshop.inward.view": "View incoming stock",
  "workshop.inward.manage": "Add incoming stock",
  "workshop.jobcard.view": "View job cards",
  "workshop.jobcard.manage": "Create and edit job cards",
  "workshop.jobcard.finalise": "Complete job cards",
  "workshop.servicebill.view": "View service bills",
  "workshop.servicebill.manage": "Create and edit service bills",
  "workshop.servicebill.pay": "Pay service bills",
  "workshop.replacement.view": "View supplier replacements",
  "workshop.replacement.manage": "Create and edit supplier replacements",
  "admin.rbac.manage": "Manage roles and user access",
  "admin.audit_log.view": "View the audit log",
  "notifications.view": "View notifications",
  "notifications.manage_rules": "Set who gets notified, and when",
  "notifications.manage_templates": "Edit notification messages",
  "notifications.test_send": "Send test notifications",
  "attachments.view": "View attachments",
  "attachments.create": "Upload attachments",
  "attachments.download": "Download attachments",
  "attachments.delete": "Delete attachments",
} satisfies Record<Leaves<typeof PERMS>, string>;
const areas: Record<string, string> = {
  accounts: "Vendor payments",
  lorry_receipt: "Lorry receipts (LR)",
  order: "Orders",
  trip: "Trips",
  vehicle_journey: "Vehicle journeys",
  trip_expense: "Trip expenses",
  trip_advance: "Driver advances",
  logslip: "Log slips",
  vp_schedule: "VP schedule",
  vp_loading: "VP loading",
  mrrr: "MR / RR",
  grn: "GRN at rail head",
  rail_branch_grn: "GRN at branch",
  rail_rake_operation: "Rail rake operations",
  rake_at_rail_head: "Rake & DC/WC at rail head",
  rake_at_branch: "Rake & DC/WC at branch",
  delivery_challan: "Delivery challans",
  ewaybill: "E-way bills",
  tracking: "Wagon tracking",
  cashplanning: "Cash planning",
  billing: "Billing",
  receipt: "Client payments",
  ledger: "Ledgers",
  workshop: "Workshop",
  admin: "Administration",
  notifications: "Notifications",
  attachments: "Attachments",
  "masters.one-lap-tracker": "Master data: OneLap trackers",
  "masters.state": "Master data: States",
  "masters.city": "Master data: Cities",
  "masters.area": "Master data: Areas",
  "masters.transport": "Master data: Transporters",
  "masters.vehicle": "Master data: Vehicles",
  "masters.vehicle-type": "Master data: Vehicle types",
  "masters.spare-category": "Master data: Spare categories",
  "masters.spare-part": "Master data: Spare parts",
  "masters.spare-part-supplier": "Master data: Spare part suppliers",
  "masters.customer": "Master data: Customers",
  "masters.company": "Master data: Companies",
  "masters.branch": "Master data: Branches",
  "masters.route": "Master data: Routes",
  "masters.warehouse": "Master data: Warehouses",
  "masters.driver": "Master data: Drivers",
  "masters.labour": "Master data: Labour",
  "masters.goods": "Master data: Goods",
  "masters.unit-of-measure": "Master data: Units of measure",
  "masters.pump": "Master data: Fuel pumps",
  "masters.wagon": "Master data: Wagons",
  "masters.railway-freight": "Master data: Railway freight rates",
  "masters.agreement": "Master data: Agreements",
  "masters.rate-matrix": "Master data: Rate matrices",
  "masters.creditor": "Master data: Creditors",
  "masters.cash-account": "Master data: Cash accounts",
};
const readable = (value: string): string => {
  const text = value
    .replace(/([a-z])([A-Z])/g, "$1 $2")
    .replace(/[._-]+/g, " ")
    .trim();
  return text
    ? text.charAt(0).toUpperCase() + text.slice(1).toLowerCase()
    : "Other actions";
};
export const permissionAreaOf = (key: string): string => {
  const parts = key.split(".");
  return parts[0] === "masters"
    ? parts.slice(0, 2).join(".")
    : (parts[0] ?? "");
};
export const permissionAreaLabel = (moduleCode: string): string =>
  areas[moduleCode] ?? readable(moduleCode);
export const permissionLabel = (key: string): string =>
  (labels as Record<string, string>)[key] ?? readable(key);
